Readme: link to Docker Desktop and on stopping the server
TheNoim/DarkflameServer pull request #5
Opened 2021-12-09 19:41 UTC by VBMCBoy

I added a link to Docker Desktop and the command for stopping the server.

Should we also add more elaborate steps on using Docker Desktop? I've never used it, but I imagine you have to point it to the cloned repository and open a shell?

2021-12-09 21:22 UTC, TheNoim commented
> Should we also add more elaborate steps on using Docker Desktop? I've never used it, but I imagine you have to point it to the cloned repository and open a shell?

Sure. But, someone needs to do this all completely crossplatform, because also Docker Desktop differs between Windows and Mac.

2021-12-09 21:27 UTC, VBMCBoy commented
Really? Oh dear. Well I don't have a Mac, but I could write something tomorrow. If the Windows part works, this would already help quite a few people.

2021-12-09 21:29 UTC, TheNoim commented
> Really? Oh dear. Well I don't have a Mac, but I could write something tomorrow. If the Windows part works, this would already help quite a few people.

Do the windows, and I do the rest.

2021-12-09 21:46 UTC, TheNoim requested changes

2021-12-09 21:46 UTC, TheNoim commented on Docker.md
> +3. Now run `docker compose up -d --build`.
I think it is dangerous to put a `.` after a command. Users tend to copy them.

2021-12-09 21:46 UTC, TheNoim commented on Docker.md
> +- Docker ([Docker Desktop](https://hub.docker.com/editions/community/docker-ce-desktop-windows/) or on Linux normal Docker)
Extend with https://hub.docker.com/editions/community/docker-ce-desktop-mac/

2021-12-10 19:43 UTC, VBMCBoy commented
I pushed a first draft for Windows install instructions. I also have images for each step, that I'll include shortly.
Also I noticed that submodules are not downloaded when downloading a ZIP of the repository, this may be a usability issue.

2021-12-12 09:46 UTC, TheNoim commented
Sorry, I just want you to know, I am currently ill. I will look into it when I feel good again.

2021-12-12 09:52 UTC, VBMCBoy commented
Oh, no rush, this can wait. Get well soon!

2021-12-14 19:01 UTC, TheNoim approved these changes
Really like it.

2021-12-14 19:01 UTC, merged